spring.application.name=ArttuApplication
server.port=${PORT:8081}

# DATABASE CONFIG
# Verifica sa fie portul si numele corect (5433 / partnersdatabaseupdated)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/partnersdatabaseupdated}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# Aceasta linie dezactiveaza stergerea automata
spring.jpa.hibernate.ddl-auto=none

# Auto-initialize the database schema
spring.sql.init.mode=always

# Enable Cross-Domain Session Capabilities for Render (Required for detached frontend/backend)
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true